Repository palantir/gradle-jdks, pull requests merged in 2022-06, with the labels that each got.

#55 Handle older glibc in libc autodetection
  changelog/@unreleased/pr-55.v2.yml
  gradle-jdks/src/integTest/java/com/palantir/gradle/jdks/OsTest.java
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/Os.java
Labels: autorelease, merge when ready

#56 Do not put jdks in ~/.gradle/caches
  changelog/@unreleased/pr-56.v2.yml
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/JdksPlugin.java
Labels: autorelease, merge when ready

#62 Improved readme
  README.md
Labels: autorelease, merge when ready, no changelog

#64 Readme typo fixes
  README.md
Labels: no changelog

#68 Add better support for Windows
  changelog/@unreleased/pr-68.v2.yml
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/JdkManager.java
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/SystemTools.java
Labels: autorelease, merge when ready

#73 Lock jdk creation using file locks
  build.gradle
  changelog/@unreleased/pr-73.v2.yml
  gradle-jdks/build.gradle
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/JdkManager.java
Labels: autorelease, merge when ready

#74 Remove self from build to fix publishing
  build.gradle
Labels: autorelease, merge when ready, no changelog

#75 Add diagnostic logging to JdkManager
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/JdkManager.java
Labels: merge when ready, no changelog

#77 JdkManager double-checks the target location once a lock is held
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/JdkManager.java
Labels: autorelease, merge when ready, no changelog
