Repository palantir/gradle-jdks, pull requests merged in 2022-05, with the labels that each got.

#15 Fix publishing
  changelog/@unreleased/pr-15.v2.yml
  gradle-jdks/build.gradle
Labels: autorelease, merge when ready

#19 Allow lazier configuration of jdks
  build.gradle
  changelog/@unreleased/pr-19.v2.yml
  gradle-jdks/build.gradle
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/GradleJdksJavaInstallationMetadata.java
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/JdkDownloader.java
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/JdkDownloaders.java
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/JdkManager.java
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/JdksExtension.java
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/JdksPlugin.java
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/LazilyConfiguredMapping.java
  gradle-jdks/src/test/java/com/palantir/gradle/jdks/LazilyConfiguredMappingTest.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#26 Expose :gradle-jdks-distributions as api
  changelog/@unreleased/pr-26.v2.yml
  gradle-jdks/build.gradle
Labels: autorelease

#27 Remove unused code
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/internal/InternalJdksPlugin.java
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/latest/LatestJdksPlugin.java
Labels: merge when ready, no changelog

#23 Palantir CA Plugin
  changelog/@unreleased/pr-23.v2.yml
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/AmazonCorrettoJdkDistribution.java
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/AzulZuluJdkDistribution.java
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/JdkRelease.java
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/JdksExtension.java
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/Os.java
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/PalantirCa.java
  gradle-jdks/src/test/groovy/com/palantir/gradle/jdks/PalantirCaPluginIntegrationSpec.groovy
Labels: autorelease

#29 Do not use atomic move to move jdks
  changelog/@unreleased/pr-29.v2.yml
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/JdkManager.java
Labels: autorelease

#33 Use gradle-utils LazilyConfiguredMapping
  changelog/@unreleased/pr-33.v2.yml
  gradle-jdks/build.gradle
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/JdksExtension.java
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/LazilyConfiguredMapping.java
  gradle-jdks/src/test/java/com/palantir/gradle/jdks/LazilyConfiguredMappingTest.java
  versions.lock
  versions.props
Labels: autorelease

#39 Fix CME in JdkDownloaders
  changelog/@unreleased/pr-39.v2.yml
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/JdkDownloaders.java
Labels: autorelease

#41 The Azul JDK distribution uses tar.gz everywhere except windows
  changelog/@unreleased/pr-41.v2.yml
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/AzulZuluJdkDistribution.java
  gradle-jdks/src/test/groovy/com/palantir/gradle/jdks/AzulZuluJdkDistributionTest.java
Labels: autorelease, merge when ready

#46 musl/alpine linux support
  .circleci/config.yml
  .circleci/template.sh
  build.gradle
  changelog/@unreleased/pr-46.v2.yml
  gradle-jdks/build.gradle
  gradle-jdks/src/integTest/java/com/palantir/gradle/jdks/OsTest.java
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/AmazonCorrettoJdkDistribution.java
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/AzulZuluJdkDistribution.java
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/Os.java
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/PalantirCa.java
  gradle-jdks/src/test/groovy/com/palantir/gradle/jdks/AzulZuluJdkDistributionTest.java
Labels: autorelease, merge when ready
