Repository palantir/gradle-jdks, pull requests merged in 2025-05, with the labels that each got.

#534 Disable Gradle JDK Automanagement workflow when running on mingw
  changelog/@unreleased/pr-534.v2.yml
  gradle-jdks-setup-common/src/main/java/com/palantir/gradle/jdks/setup/common/CurrentOs.java
  gradle-jdks-setup/src/main/resources/gradle-jdks-functions.sh
  gradle-jdks-setup/src/main/resources/gradle-jdks-setup.sh
Labels: autorelease, merge when ready

#536 Allow `palantir-gradle-jdks` idea plugin dependency configuration via `idea-configuration plugin`
  changelog/@unreleased/pr-536.v2.yml
  gradle-jdks-groovy/build.gradle
  gradle-jdks-groovy/src/main/groovy/com/palantir/gradle/jdks/ConfigureJdksIdeaPluginXml.groovy
  gradle-jdks-groovy/src/test/groovy/com/palantir/gradle/jdks/ConfigureJdksIdeaPluginXmlTest.groovy
  gradle-jdks-groovy/src/test/resources/expected-externalDependencies.xml
  gradle-jdks/build.gradle
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/PalantirGradleJdksIdeaPlugin.java
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/ToolchainsPlugin.java
  settings.gradle
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#549 Use `eval` explicitly
  gradle-jdks-setup/src/main/resources/gradle-jdks-functions.sh
  gradle-jdks-setup/src/main/resources/gradle-jdks-setup.sh
Labels: merge when ready, no changelog

#544 bump `gradle-idea-configuration` and move off deprecated methods
  changelog/@unreleased/pr-544.v2.yml
  gradle-jdks/src/main/java/com/palantir/gradle/jdks/ToolchainsPlugin.java
  versions.lock
  versions.props
Labels: merge when ready
